### PR TITLE
Jekyll -- Windows compatibility

### PR DESCRIPTION
**Pull request by rcarlis**
add condition to allow windows to run the bat for spawn http://stackoverflow.com/questions/17516772/using-nodejss-spawn-causes-unknown-option-and-error-spawn-enoent-err/17537559#17537559

### CODE REVIEW

**Comment by wjramos** [comment]
Updated title for clarity

**Comment by mhewson** [comment]
approve

[Approved with PullApprove](https://pullapprove.com/rei/rei-cedar/pull-request/59/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=rei/rei-cedar)

**Comment by wjramos** [comment]
@rcarlis there are now conflicts -- is this something you still wanted to merge?

**Comment by rcarlis** [comment]
updated to resolve the conflict

**Comment by rcarlis** [comment]
would you guys pull/build and confirm that the changes I made don't break mac?

**Comment by wjramos** [comment]
Confirmed -- works fine in unix-style environment

**Pull request merged**
