### PR TITLE
Css usage report

### PR DESCRIPTION
**Pull request by megafatsquirrel**
1. Pull branch
2. `npm install`
3. `npm run ucss`

After step 3 you should see the pages getting crawled and a report will be printed to the command line.

### CODE REVIEW

**Comment by mhewson** [comment]
approved 

[Approved with PullApprove](https://pullapprove.com/rei/rei-cedar/pull-request/150/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=rei/rei-cedar)

**Comment by robatron** [comment]
If you use [npm scripts](https://docs.npmjs.com/misc/scripts), you don't have to install ucss globally, e.g., if you add something like `"ucss": "ucss"` in "scripts" in _package.json_, you can invoke it via `npm run ucss`, no global install required :)

**Comment by megafatsquirrel** [comment]
@robatron Thanks! I like that trick.

...also don't you work somewhere else now... :P

**Comment by robatron** [comment]
Nah, we all work at Open Source, Inc. ;-)

BTW, I recently noticed our style guide is available publically: http://www.zillowstatic.com/static-zsg/LATEST/styleguide/index.html. Check it out if you're interested! (CC @mhewson)

**Comment by megafatsquirrel** [comment]
What do you use for searching the site?

**Comment by robatron** [comment]
We just generate a JSON file alongside the HTML pages when generating the static site that contains keywords and links, then use JS to load the file, match the term, and redirect to the associated link: http://www.zillowstatic.com/static-zsg/LATEST/styleguide/index.json

**Comment by mhewson** [comment]
approve

[Approved with PullApprove](https://pullapprove.com/rei/rei-cedar/pull-request/150/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=rei/rei-cedar)

**Pull request merged**
