### PR TITLE
re-map remaining pre-release color tokens

### PR DESCRIPTION
**Pull request by cowills**
🎉 🎉

### CODE REVIEW

**Comment by mhewson** [comment]
Adding James on as a reviewer to get some design eyes on this per https://issues.rei.com/browse/CDR-961

**Comment by cowills** [comment]
> Adding James on as a reviewer to get some design eyes on this per https://issues.rei.com/browse/CDR-961

these changes have already been reviewed by James

**Review by lancetharper — APPROVED** [review]
🙌

**Comment by mhewson** [comment]
Well then lets get that story out of the backlog @arniebradfo :0

**Comment by arniebradfo** [comment]
@mhewson k its 'DONE' now

**Pull request merged**
