### PR TITLE
Update packages, replace deprecated packages

### PR DESCRIPTION
**Pull request by wjramos**

### CODE REVIEW

**Comment by mhewson** [comment]
:+1: ApPrOvE -- lets get this in before flex and run the visual regression

**Comment by mhewson** [comment]
mhewson@C02NT179G3QP ~/code/rei-cedar (update-deps)$ gulp
/Users/mhewson/code/rei-cedar/gulpfile.js:355
s:test:post-clean', [ 'js:test:qunit' ], function() { return del( [ `${ PATHS.
                                                                    ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

**Comment by wjramos** [comment]
Likely related to version of node. I can change this from template strings to regular concatenation

**Comment by wjramos** [comment]
Yup -- Template strings and other es6 features are supported in node 4+ (I assume you are using 0.12), I will update this for more backwards compatibility between versions of node

**Comment by mhewson** [comment]
brew upgrade node - working now
maybe a note in the readme on node vision requirements?

**Comment by wjramos** [comment]
I removed the template strings, so it should be more backwards compatible

**Comment by mhewson** [comment]
getting a fail on npm run test-ui
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0

**Comment by wjramos** [comment]
@mhewson Good to merge?

**Comment by wjramos** [comment]
@mhewson we good?

**Comment by mhewson** [comment]
yes sir

**Pull request merged**
