### PR TITLE
upgrade jquery 2.0.3 to 2.2.4, using regular jquery instead of jquery2

### PR DESCRIPTION
**Pull request by ghost**
There is no need to use jquery2 instead of jquery, the jquery bug leaking $ to global has been fixed for a while now.

I've changed dependencies to point to the official jquery npm release. I've also done some manual testing via the generated documentation as well as running the automated tests.

cc @peripateticus @megafatsquirrel

### CODE REVIEW

**Comment by megafatsquirrel** [comment]
Approve

[Approved with PullApprove](https://pullapprove.com/rei/rei-cedar/pull-request/151/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=rei/rei-cedar)

**Comment by megafatsquirrel** [comment]
This will be merged after we make a release from some previous changes.

**Comment by peripateticus** [comment]
Nice! 👍

**Comment by wjramos** [comment]
dope 👍

**Pull request merged**
