### PR TITLE
General cleanup

### PR DESCRIPTION
**Pull request by bonpixel**
Fixing a few things and adding a shrinkwrap since the new less version makes everything wonky. For now were are locking at 2.5.3 until we can sort it all out.

### CODE REVIEW

**Comment by agats** [comment]
:+1:
Good idea with the shrink wrap. Also, out of curiosity did the `npm shrinkwrap` automatically alphabatize the json?

**Comment by bonpixel** [comment]
:confused:  Huh, I didn't notice that until you pointed it out. I'm not sure but that seems like a good guess.

**Comment by codetothepoint** [comment]
I remember having issues without shrinkwrap alphabetization in the past.  A lack of alphabetization caused severe merge conflicts.

**Comment by codetothepoint** [comment]
But, ya - go for it!  Merge away!

**Comment by robatron** [comment]
FEBS has a shrinkwrap stabilizer, `febs-shrinkwrap`, to address that issue.

**Comment by codetothepoint** [comment]
What does this Outlander know of FEBS....?  ;-)

**Pull request merged**
