### PR TITLE
fix(caption): cite browser default is font style italic design would…

### PR DESCRIPTION
**Pull request by mhewson**
… like this to be normal

### Design:
- [ ] Reviewed with designer and meets expectations

### Cross-browser testing:
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE11
- [ ] iOS
- [ ] Android

### Visual regression testing:
- [ ] Added/updated backstop tests
- [ ] Passes with existing reference images (or failed as expected)

### Unit testing:
- [ ] Sufficient unit test coverage (see unit test best practices for ideas)

### A11y:
- [ ] Meets WCAG AA standards

### Documentation:
- [ ] API docs created/updated
- [ ] Examples created/updated

### CODE REVIEW

**Comment by lancetharper** [comment]
Should this be all cites or just within the caption component?

**Comment by mhewson** [comment]
I thought of placing this in reset but thought it could be a bit heavy handed as they are specifically calling out this instance in which we have used a `cite` tag

**Review by cowills — APPROVED** [review]

**Comment by lancetharper** [comment]
This should have used the class and not styled the element tag

**Comment by cowills** [comment]
> This should have used the class and not styled the element tag

its scoped to this component, so it only applies to `cite`'s inside a cdr-caption.

**Pull request merged**
